### ISSUE TITLE
Hosts file

### ISSUE THREAD

**Issue by Duna** [Juve-yescas/Block-Ads-TpLink#1]
Please update the hosts file with an updated hosts list

**Comment by Duna** [comment]
Dns:
[Uploading dns_filter_15.txt…]()

**Comment by Duna** [comment]
Filters:
[filter_2.txt](https://github.com/Juvenal-Yescas/Block-Ads-TpLink/files/5975655/filter_2.txt)
[filter_3.txt](https://github.com/Juvenal-Yescas/Block-Ads-TpLink/files/5975656/filter_3.txt)
[filter_4.txt](https://github.com/Juvenal-Yescas/Block-Ads-TpLink/files/5975657/filter_4.txt)
[filter_11.txt](https://github.com/Juvenal-Yescas/Block-Ads-TpLink/files/5975658/filter_11.txt)

**Comment by Duna** [comment]
"exclude": [
        "*://mil.ru/*",
        "*wikipedia.org*",
        "*icloud.com*",
        "*hangouts.google.com*",
        "*www.facebook.com/plugins/*",
        "*www.facebook.com/v*/plugins*",
        "*disqus.com/embed/comments*",
        "*vk.com/widget*",
        "*twitter.com/intent/*",
        "*www.youtube.com/embed/*",
        "*player.vimeo.com*",
        "*coub.com/embed*",
        "*staticxx.facebook.com/connect/xd_arbiter/*",
        "*vk.com/q_frame*",
        "*tpc.googlesyndication.com*",
        "*syndication.twitter.com*",
        "*platform.twitter.com*",
        "*tutosdeath.blogspot.com*",
        "*notifications.google.com*",
        "*google.com/recaptcha/*",
        "*bizmania.ru/*"
    ]

**Comment by juvenal-yescas** [comment]
@Duna  Sorry, but tp link does not support blocking many hosts, it is only basic, I recommend [pi-hole](https://github.com/pi-hole/pi-hole) or [AdGuardHome](https://github.com/AdguardTeam/AdGuardHome)
